export const mockProducts = [
    {
        _id: "1",
        title: "Wireless Noise-Cancelling Headphones",
        sku: "ELEC-HEAD-001",
        description: "Over-ear headphones with active noise cancellation, 30-hour battery life, and plush memory-foam ear cushions for all-day comfort.",
        shortDescription: "Premium ANC headphones with 30-hour battery life.",
        price: 6000,
        discountPrice: { type: "percentage", value: 25, startDate: "2026-07-01", endDate: "2026-07-31" },
        salePrice: 4500,
        stock: 12,
        category: "Electronics",
        brand: "SoundCore",
        tags: ["audio", "wireless", "noise-cancelling"],
        additionalInformation: "Includes carrying case and USB-C charging cable.",
        status: "active",
        images: [
            { url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600", isMain: true },
            { url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600", isMain: false },
            { url: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600", isMain: false },
        ],
        averageRating: 4.5,
        numReviews: 128,
    },
    {
        _id: "2",
        title: "Minimalist Leather Backpack",
        sku: "FASH-BAG-002",
        description: "Full-grain leather backpack with padded laptop sleeve, water-resistant lining, and adjustable straps. Fits up to a 15-inch laptop.",
        shortDescription: "Full-grain leather backpack with laptop sleeve.",
        price: 3200,
        discountPrice: { type: "none", value: 0 },
        salePrice: 3200,
        stock: 8,
        category: "Fashion",
        brand: "Urban Craft",
        tags: ["leather", "backpack", "laptop"],
        additionalInformation: "Available in navy and charcoal.",
        status: "active",
        images: [
            { url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600", isMain: true },
            { url: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600", isMain: false },
        ],
        averageRating: 4.2,
        numReviews: 64,
    },
    {
        _id: "3",
        title: "Ceramic Pour-Over Coffee Set",
        sku: "HOME-COF-003",
        description: "Hand-glazed ceramic dripper and carafe set. Includes reusable stainless steel filter. Makes up to 4 cups.",
        shortDescription: "Hand-glazed ceramic pour-over set, makes 4 cups.",
        price: 2400,
        discountPrice: { type: "percentage", value: 25, startDate: "2026-07-01", endDate: "2026-07-31" },
        salePrice: 1800,
        stock: 20,
        category: "Home & Living",
        brand: "Terra Studio",
        tags: ["coffee", "ceramic", "kitchen"],
        additionalInformation: "Hand wash recommended.",
        status: "active",
        images: [
            { url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600", isMain: true },
            { url: "https://images.unsplash.com/photo-1495612200-1a3e6a5b1e42?w=600", isMain: false },
        ],
        averageRating: 4.8,
        numReviews: 41,
    },
    {
        _id: "4",
        title: "The Design of Everyday Things",
        sku: "BOOK-UX-004",
        description: "Don Norman's classic on human-centered design — a must-read for anyone building products people actually enjoy using.",
        shortDescription: "Classic book on human-centered design.",
        price: 950,
        discountPrice: { type: "none", value: 0 },
        salePrice: 950,
        stock: 35,
        category: "Books",
        brand: "Basic Books",
        tags: ["design", "ux", "non-fiction"],
        additionalInformation: "Paperback, 368 pages.",
        status: "active",
        images: [{ url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600", isMain: true }],
        averageRating: 4.7,
        numReviews: 210,
    },
    {
        _id: "5",
        title: "Matte Skincare Gift Set",
        sku: "BEAU-SKN-005",
        description: "A five-piece set including cleanser, toner, serum, moisturizer, and SPF — formulated for combination skin.",
        shortDescription: "5-piece skincare set for combination skin.",
        price: 2800,
        discountPrice: { type: "percentage", value: 25, startDate: "2026-07-01", endDate: "2026-07-31" },
        salePrice: 2100,
        stock: 15,
        category: "Beauty",
        brand: "Glow Lab",
        tags: ["skincare", "gift-set"],
        additionalInformation: "Cruelty-free, dermatologist tested.",
        status: "active",
        images: [
            { url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600", isMain: true },
            { url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600", isMain: false },
        ],
        averageRating: 4.3,
        numReviews: 88,
    },
    {
        _id: "6",
        title: "Adjustable Yoga Mat & Strap Set",
        sku: "SPRT-YOG-006",
        description: "6mm eco-friendly TPE yoga mat with alignment lines, paired with an adjustable cotton strap for deeper stretches.",
        shortDescription: "Eco-friendly TPE yoga mat with alignment lines.",
        price: 2000,
        discountPrice: { type: "percentage", value: 25, startDate: "2026-07-01", endDate: "2026-07-31" },
        salePrice: 1500,
        stock: 0,
        category: "Sports",
        brand: "FlexFit",
        tags: ["yoga", "fitness"],
        additionalInformation: "Includes carrying strap.",
        status: "active",
        images: [{ url: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=600", isMain: true }],
        averageRating: 4.0,
        numReviews: 19,
    },
];