export const mockUser = [
    {
        _id: "u1",
        name: "Ashraf Hossain",
        email: "ashraf@example.com",
        phone: "01712345678",
        role: "customer",
        status: "active",
        joined: "2026-03-14",
    },
    {
        _id: "u2",
        name: "Nusrat Jahan",
        email: "nusrat@example.com",
        phone: "01898765432",
        role: "customer",
        status: "active",
        joined: "2026-04-02",
    },
    {
        _id: "u3",
        name: "Tanvir Ahmed",
        email: "tanvir@example.com",
        phone: "01611223344",
        role: "admin",
        status: "active",
        joined: "2026-01-20",
    },
    {
        _id: "u4",
        name: "Farhana Akter",
        email: "farhana@example.com",
        phone: "01555667788",
        role: "customer",
        status: "suspended",
        joined: "2026-05-11",
    },
    {
        _id: "u5",
        name: "Rakibul Islam",
        email: "rakibul@example.com",
        phone: "01922334455",
        role: "customer",
        status: "active",
        joined: "2026-06-18",
    },
];